### ISSUE TITLE
DIY for bar@_axes.py

### ISSUE THREAD

**Issue by filippaleuckfeld** [filippaleuckfeld/matplotlib#11]

**Comment by alexbinett** [comment]
coverage -- 51/57: 89.47368421052632%: [True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, False, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
