### ISSUE TITLE
DIY for hexbin@_axes.py

### ISSUE THREAD

**Issue by filippaleuckfeld** [filippaleuckfeld/matplotlib#14]

**Comment by cbystam** [comment]
Before new tests:
coverage -- 37/61: 60.65573770491803%: [True, True, False, False, False, True, True, False, True, True, True, True, True, True, True, True, True, False, True, False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, False, True, True, False, True, True, False, True, True, True, True, True, True, False, False, False, True, True, True, True, True, True, True, True, True, True, True]

**Comment by cbystam** [comment]
After 2 tests:
coverage -- 44/61: 72.1311475409836%: [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, True, True, True, True, True, True, False, True, True, True, True, True, True, False, False, False, True, True, True, True, True, True, True, True, True, True, True]
Edit: Sorry, misunderstood that the DIY and tests should be in different branches...

**Comment by cbystam** [comment]
Refactoring ideas:
The hexbin function is very long with almost 200 lines, so one idea would be to try to divide it up into several functions.
The code handling the C parameter contains 15 branches, which is a fourth of all branches in this function. This could perhaps be separated into its own function. 
There is also a relatively large for-loop which handles marginal, and contains 8 branches. This could also be written as its own function.

**Comment by II-Day-II** [comment]
Closing this, make sure to put the documentation things in the report

**Comment by cbystam** [comment]
Added another part in testing which connects it to requirements (don't know why the commit wasn't connected to this issue...?).
