### ISSUE TITLE
Count cyclomatic complexity of bar@_axes.py by hand

### ISSUE THREAD

**Issue by haval0** [filippaleuckfeld/matplotlib#4]
Two people need to check this for the function. Add to the report when finished

**Comment by cbystam** [comment]
Using the formula on the slides, M = pi - s + 2, I only get 29 branches. I don't know if I'm missing something, though.

**Comment by alexbinett** [comment]
I got M = 27 (29-4+2). I also followed that formula with the addition of counting the try block as a decision point. Did you count the raise (throw) function as an exit point?

**Comment by cbystam** [comment]
Yes, I find three throw errors and one return statement, so I get s = 4 as well. Today I get 28 decision points however (2 try blocks, 24 if and 2 and/or), which gives me a total of M = 26.
Edit: M = 31 if we include for-loops.

**Comment by alexbinett** [comment]
I get M = 27 when I include for-loops (there is only one for-loop, right?). M = 26 when I don't.
