### ISSUE TITLE
Count cyclomatic complexity of boxplot@_axes.py by hand

### ISSUE THREAD

**Issue by haval0** [filippaleuckfeld/matplotlib#5]
Two people need to check this for the function. Add to the report when finished

**Comment by haval0** [comment]
Getting M = 30 (M= pi - s + 2, where pi = 32 and s = 4, formula from the slides). Lizard says 35.

**Comment by alexbinett** [comment]
Also got M = 30 when counting everything mentioned in the slides. On the wikipedia page of Cyclomatic Complexity, it says that one should count conditional loops as decision points, while in the slides they only mention while loops. Should we just follow what is on the slides? If not, M = 32.
