### ISSUE TITLE
Count cyclomatic complexity of hexbin@_axes.py by hand

### ISSUE THREAD

**Issue by haval0** [filippaleuckfeld/matplotlib#7]
Two people need to check this for the function. Add to the report when finished

**Comment by cbystam** [comment]
Using the formula on the slides, M = pi - s + 2, I only get 28 branches. Since it's 37 according to lizard, I'm not sure if I'm doing things wrong.

**Comment by haval0** [comment]
(Accidentally counted this one as well since I couldn't keep my open tabs straight..)

I counted a cyclomatic complexity of 27 using that same formula from the slides, with pi = 29 and s = 4. Since we are getting such similar answers, and far below 37, might there be an extra cause of branching that we haven't considered? I also got "too low" answers on the two other functions I counted.

Now, the assignment does not state that we must get the same results as the tool we use, so if we can find the reason for our discrepancy of 1 (27 vs 28, why?), then I think we can use our current answer.

specifically the quote from the assignment:
> What are your results? Did everyone get the same result? Is there something that is unclear? **_If you have a tool, is its result the same as yours?_**

**Comment by cbystam** [comment]
When doing a recount today I also get pi = 29 and s = 4. Tired brain on Friday, hehe.

**Comment by II-Day-II** [comment]
Using `M = pi - s + 2` where `pi = 29` and `s = 4` I get `M = 27`.

Should we be counting the exit conditions of loops as well? I saw 5 loops in this function, which would increase `M` to 32.

**Comment by cbystam** [comment]
I haven't done so in my calculations, but if while-loops should be included, for loops should maybe also be so. I find 7 for-loops, however. ( Lines 4951, 4952, 4953, 4962, 4963, 5055 and 5076)

**Comment by II-Day-II** [comment]
You're right, there are 7 loops including the list comprehensions. `M = 34` if they are included, 27 otherwise.
