### ISSUE TITLE
Count cyclomatic complexity of _spectral_helper@mlab.py by hand

### ISSUE THREAD

**Issue by haval0** [filippaleuckfeld/matplotlib#8]
Two people need to check this for the function. Add to the report when finished

**Comment by II-Day-II** [comment]
Using `M = pi - s + 2` where `pi = 38` and `s = 3` I get `M = 37`.

**Comment by filippaleuckfeld** [comment]
I also get `pi = 38` and `s = 3` (with two raise and one return statement)
